import {
  SiAxios,
  SiCss3,
  SiCssmodules,
  SiDjango,
  SiExpress,
  SiGit,
  SiGithub,
  SiHibernate,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostcss,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiReact,
  SiShadcnui,
  SiSpring,
  SiStorybook,
  SiStyledcomponents,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si'
import { DiJava } from 'react-icons/di'

export const languages = [
  {
    svg: <SiHtml5 className="text-[#E34F26]" />,
    text: 'HTML5',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    svg: <SiCss3 className="text-[#1572B6]" />,
    text: 'CSS3',
    link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  {
    svg: <SiTailwindcss className="text-[#06B6D4]" />,
    text: 'Tailwindcss',
    link: 'https://tailwindcss.com/docs/installation',
  },
  {
    svg: <SiShadcnui className="text-white" />,
    text: 'Shadcnui',
    link: 'https://ui.shadcn.com/',
  },
  {
    svg: <SiPostcss className="text-[#DD3A0A]" />,
    text: 'Postcss',
    link: 'https://postcss.org/docs/',
  },
  {
    svg: <SiJavascript className="text-[#F7DF1E]" />,
    text: 'Javascript',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  {
    svg: <SiTypescript className="text-[#3178C6]" />,
    text: 'TypeScript',
    link: 'https://www.typescriptlang.org/docs/',
  },
  {
    svg: <SiReact className="text-[#61DAFB]" />,
    text: 'ReactJS',
    link: 'https://react.dev/',
  },
  {
    svg: <SiJest className="text-[#ff6171]" />,
    text: 'Jest',
    link: 'https://jestjs.io/',
  },
  {
    svg: <SiNodedotjs className="text-[#339933]" />,
    text: 'NodeJs',
    link: 'https://nodejs.org/en/docs',
  },
  {
    svg: <SiNestjs className="text-[#E0234E]" />,
    text: 'NestJs',
    link: 'https://nestjs.com/',
  },
  {
    svg: <SiExpress className="text-white" />,
    text: 'Express',
    link: 'https://expressjs.com/',
  },
  {
    svg: <SiNextdotjs className="text-white" />,
    text: 'NextJs',
    link: 'https://nextjs.org/',
  },
  {
    svg: <SiPrisma className="text-white" />,
    text: 'Prisma',
    link: 'https://www.prisma.io/',
  },
  {
    svg: <SiAxios className="text-[#5A29E4]" />,
    text: 'Axios',
    link: 'https://axios-http.com/docs/intro',
  },
  {
    svg: <SiStyledcomponents className="text-[#DB7093]" />,
    text: 'Styled Components',
    shortText: 'Styled C.',
    link: 'https://styled-components.com/',
  },
  {
    svg: <SiCssmodules className="text-white" />,
    text: 'CSS Modules',
    link: 'https://github.com/css-modules/css-modules',
  },
  {
    svg: <SiStorybook className="text-[#FF4785]" />,
    text: 'Storybook',
    link: 'https://storybook.js.org/',
  },
  {
    svg: <SiGit className="text-[#F05032]" />,
    text: 'Git',
    link: 'https://git-scm.com/',
  },
  {
    svg: <SiGithub className="text-white" />,
    text: 'GitHub',
    link: 'https://github.com/',
  },
  {
    svg: <SiPython className="text-[#3776AB]" />,
    text: 'Python',
    link: 'https://www.python.org/',
  },
  {
    svg: <SiDjango className="text-[#092E20]" />,
    text: 'Django',
    link: 'https://www.djangoproject.com/',
  },
  {
    svg: <DiJava className="text-[#744e3b]" />,
    text: 'Java',
    link: 'https://java.com/',
  },
  {
    svg: <SiHibernate className="text-[#59666C]" />,
    text: 'Hibernate',
    link: 'https://hibernate.org/',
  },
  {
    svg: <SiSpring className="text-[#6DB33F]" />,
    text: 'Spring',
    link: 'https://spring.io/projects/spring-boot',
  },
  {
    svg: <SiPostgresql className="text-[#4169E1]" />,
    text: 'PostgreSQL',
    link: 'https://www.postgresql.org/',
  },
  {
    svg: <SiPostman className="text-[#FF6C37]" />,
    text: 'Postman',
    link: 'https://www.postman.com/',
  },
  {
    svg: <SiMongodb className="text-[#47A248]" />,
    text: 'MongoDB',
    link: 'https://www.mongodb.com/docs/',
  },
  {
    svg: <SiMysql className="text-[#4479A1]" />,
    text: 'MySQL',
    link: 'https://www.mysql.com/',
  },
]
